documentation
credits
	^ HelpTopic 
		title: 'Credits'
		contents: 
'Blast Query Builder has been originally developed on Pharo by Hernán Morales Durand. The current work is sponsored by the Institute of Veterinary Genetics - National Scientific and Technical Research Council (CONICET) in Argentina. 

If you have an interest in Blast Query Builder,  ' , PCTApplication projectSite , ' is the place you want to go right away. The main developer of Blast Query Builder may be reached by sending email to hernan.morales@gmail.com
'