documentation
howToContribute
	^ HelpTopic 
		title: 'How to contribute'
		contents: 'As most open source project, you can directly contribute to Blast Query Builder in many different ways: proposing code enhancement, reporting bugs in the google code website, answering questions in the mailing list.  
Even simply trying it out and asking questions is quite valuable since it helps us to figure out how Blast Query Builder is perceived by new commers.

Project page: ' , PCTApplication projectSite