pages
page1
	^HelpTopic 
		title: '1. Loading a data set'
		contents: 'To build a query first load XML results exported from the NCBI website. Select File -> Open BLAST XML from the main menu.
		
Once loaded, you should see an information dialog for successfully loading. Please note that XML files which are truncated or not in the expected format (NCBI''s BLAST XML) will not be detected until query execution. This process only loads the file but does not verify valid contents.

You must perform and execute at least an initial query to work with the results. To explore the original data set click the icon Explore in the toolbar.
'.