pages
page3
	^HelpTopic 
		title: '3. Executing a query'
		contents: 'Query execution walks over the built filters and executes each one in turn. Execution can be cumulative (default behavior) or non-cumulative. In the cumulative configuration, each filter is executed on the previous filtered results. Non-cumulative execution generates a result set for each filter, which is useful to compare filters performance.
		
Cumulative execution and other useful settings can be changed by selecting Tools -> Options from the toolbar menu.

'